### ISSUE TITLE
Support custom command for preparing srpm

### ISSUE THREAD

**Issue by psss** [packit-service/packit-service#103]
I'm trying to [enable packit](https://github.com/psss/fmf/pull/58) for fmf. In order to prevent docs duplication the man page for `fmf` is created from README using `rst2man`. Preparing the tarball including man page using custom `post-upstream-clone` [command](https://github.com/psss/fmf/pull/58/commits/7cf0c1c) did not help. The man page is still not included in the srpm and the copr build [fails](https://copr.fedorainfracloud.org/coprs/packit/psss-fmf-58/build/1021868/).

Could you please have a look what might be wrong there? Or possibly, would it make sense to provide a custom srpm build command? In this case it would be `make srpm` which would take care of the man page as well.

**Comment by TomasTomecek** [comment]
I believe we have discussed this a bit within the team and came to the conclusion that we don't want such functionality in packit: the only problem here is to create the upstream archive, packit can handle the rest very well so that's why we think that replacing the srpm process completely doesn't make sense for packit.

Feel free to reopen if you feel otherwise.

**Comment by psss** [comment]
I see. Makes sense. But it would be good to have a little bit more easier / straightforward way how to prepare the upstream archive. For `fmf` I had to add three Makefile targets plus this:

    current_version_command: ["make", "packit-version"]

    actions:
        create-archive:
        - make packit-tarball
        - make packit-path

I believe it should be much simpler/shorter/obvious.

**Comment by TomasTomecek** [comment]
okay, let's create a dedicated issue for such use case
