### ISSUE TITLE
systemd cannot be built via packit - /sandcastle/triggers.systemd: No such file or directory

### ISSUE THREAD

**Issue by thrix** [packit-service/packit-service#138]
See https://github.com/packit-service/systemd-rhel8-flock/pulls

There was an error while running a copr build: Failed to parse SPEC file: error: Unable to open /sandcastle/triggers.systemd: No such file or directory
You can re-trigger copr build by adding a comment (/packit copr-build) into this pull request.

**Comment by TomasTomecek** [comment]
werking on it

**Comment by TomasTomecek** [comment]
In the end the problem was in rebase-helper: https://github.com/rebase-helper/rebase-helper/pull/711

It may take some time for us to get that fix in prod.

The solution in the meantime could be not to require those files in spec as Franta explains here: https://github.com/rebase-helper/rebase-helper/issues/710#issuecomment-532270644

**Comment by thrix** [comment]
@mrc0mmand can you fix that in our systemd test repo maybe?

**Comment by TomasTomecek** [comment]
I "fixed" it https://github.com/packit-service/systemd-rhel8-flock/pull/7

**Comment by thrix** [comment]
fix which will break all tests? :) mmkay :)

**Comment by TomasTomecek** [comment]
but build works, that's what this issue is about ;)

feel free to open a new issue if you also need the tests to pass

**Comment by FrNecas** [comment]
Hopefully, there should be a new release of rebase-helper fairly soon, so the problem shouldn't last too long. Sorry for the incovenience.
