### ISSUE TITLE
Broken CI

### ISSUE THREAD

**Issue by jpopelka** [packit-service/packit-service#210]
Not sure since when (maybe since #199? - @jscotka) but Zuul CI doesn't seem to work. (see #207, #208)

```
TASK [wait for tests to finish]
task path: /home/zuul-worker/src/github.com/packit-service/packit-service/files/check-inside-openshift.yaml:52
fatal: [localhost]: FAILED! => {"changed": true, "cmd": ["oc", "wait", "job/packit-tests", "--for", "condition=complete", "--timeout=300s"], ... "stderr": "error: timed out waiting for the condition", "stderr_lines": ["error: timed out waiting for the condition"]
[localhost] TASK: wait for tests to finish (debug)> User interrupted execution
make: *** [Makefile:77: check-inside-openshift-zuul] Error 99
```

**Comment by jscotka** [comment]
There were more issues, what start it failing:
 - several PR what was started before these tests were fixed ans was not rebased before merge.
 - some of these PRs touched COPR part of packit service, what is covered by these tests.
 - it is nontrivial to debug it ansible+OS (because you have no logs from machine in case it fail)

There were enough to regenerate files and it started PASS again https://github.com/packit-service/packit-service/pull/211

And possible AI would be to improve ansible+openstack debugging (eg) somehow run it, not fail, return results and then pass/fail based on status of run command, to avoid, that ansible inside openshift hides deeper information what happen there.

**Comment by jpopelka** [comment]
Thanks for investigation!
