### ISSUE TITLE
Verbose mode for comments

### ISSUE THREAD

**Issue by yarda** [packit-service/packit-service#243]
~~`trigger: pull_request` doesn't re-trigger on force push. Is there a way how to achieve re-build/re-testing upon force push?~~

Have an option to add a new comment after each built.

*edited by @lachmanfrantisek*

**Comment by lachmanfrantisek** [comment]
Still relevant.

**Comment by lachmanfrantisek** [comment]
@TomasTomecek 

After we merge your PR with logs, this needs to be redesign.

What about this:
- By default, no comments and everything is accessible via status URL.
- If the verbose mode is configured, add a comment after each run:
  - zuul-like format (list of all chroots)  -- harder since we receive response per chroot
  - one-comment-per target (a lot of spam)
  - only error messages (like the current behaviour)

**Comment by TomasTomecek** [comment]
honestly, since we have our own status page now, I'd disable all commenting, maybe even the congrats comment - we can discuss when I get back

**Comment by TomasTomecek** [comment]
https://github.com/packit-service/packit-service/pull/447 is now merged (and will be deployed in the next cycle, meaning on Monday). That PR should resolve this issue: packit-service now has a status page for every build with info and logs - the logs should be present even when the SRPM creation fails.

I'm closing this issue - feel free to reopen if the proposed solution doesn't work for you.
