### ISSUE TITLE
Synchronize lookaside cache and distgit

### ISSUE THREAD

**Issue by lachmanfrantisek** [packit-service/packit-service#360]
Make sure that we have the right archive in the lookaside cache when the distgit PR is merged.

Some ideas:
- Overwrite the archive on each run.
- Allows option/command in the service as we have in the CLI:
```
  --force-new-sources     Upload the new sources also when the archive is
                          already in the lookaside cache.
```
- Resubmit the archive on the distgit PR merge.

**Comment by lachmanfrantisek** [comment]
@m4rtink

**Comment by TomasTomecek** [comment]
How do we know what's the correct archive?

**Comment by jpopelka** [comment]
@M4rtinK do you think this is still valid?

From our discussion:
We should compare the archives we have in lookaside cache vs. what we have locally.

**Comment by M4rtinK** [comment]
@jpopelka I don't see why this would no longer be valid - packit needs to make sure that merging its generated PR & putting the tarball corresponding to the PR is an atomic transaction.

Otherwise this functionality is simply not safe to use:
- a PR changing spec file could be merged without the given spec file being in place - this is basically instant breakage
- a tarball could be put into distgit without the PR being merged/PR being closed - this is less critical, but could cause issues later on when trying to do another build with tarball with the same version already in lookaside cache

BTW, I guess that actually the tarball tracking in lookaside cache works on file hashes. If it always does a hash of the tarball, then I guess packit could always add the tarball to the lookaside cache when creating the PR. The PR would then include change to the sources file changing the hash to one corresponding to the tarball for the pull request.

That should work IMHO & should be atomic. The only issue I can think of is that there could now be multiple tarballs with the same name but different content in the lookaside cache & the size of the cache would be bigger per package due to all the "useless" tarballs corresponding to PRs that have been closed.

**Comment by lachmanfrantisek** [comment]
@M4rtinK thanks for repeating your proposal here. It's some time we discuss that...

How can we have multiple versions of the source archive? (We don't build archives during `propose-downstream`. We just download it.)

In packit CLI, we have `--force-new-sources` option. (See below.)
 - Do we want to have this as a config option also for packit-as-a-service?
 - Do we want this behaviour by default?

```
packit propose-update --help
Packit 0.8.2.dev143+g96dd432 is being used.
Usage: packit propose-update [OPTIONS] [PATH_OR_URL] [VERSION]

  Release current upstream release into Fedora

  PATH_OR_URL argument is a local path or a URL to the upstream git
  repository, it defaults to the current working directory

  VERSION argument is optional, the latest upstream version will be used by
  default

Options:
  : 
  :
  --force-new-sources     Upload the new sources also when the archive is
                          already in the lookaside cache.
  :
  :
  -h, --help              Show this message and exit.
```

**Comment by M4rtinK** [comment]
```
  --force-new-sources     Upload the new sources also when the archive is
                          already in the lookaside cache.
```
I'm not sure how this is supposed to work - what does "archive already is in the lookaside cache" mean ?

Archive with the same version in its name but different content ? (you can do a checksum of "your" archive and then compare it with checksum of the archive in lookaside cache)

In any case, I would recommend to replace the tarball by default for propose update, if you can detect the tarballs are different, or else you risk pushing spec file change without the necessary changes in the tarball (if I understand things correctly).

**Comment by lachmanfrantisek** [comment]
> (you can do a checksum of "your" archive and then compare it with checksum of the archive in lookaside cache)

This is maybe the source of confusion. There is no "our" archive. We don't create any archive.

> I'm not sure how this is supposed to work - what does "archive already is in the lookaside cache" mean ?

Currently, it goes like this:
- Get the archive name from the spec-file.
  - If the archive with that name is already in the lookaside-cache **and** it is not in the `sources` file, nothing will happen.
  - Otherwise:
    - Download the upstream archive using the info from specfile.
    - Use `fedpkg new-sources` to update distgit files (`sources` and `.gitignore`) and upload the archive to the lookaside-cache.

> Archive with the same version in its name but different content ?

Yes


> In any case, I would recommend to replace the tarball by default for propose update, if you can detect the tarballs are different, or else you risk pushing spec file change without the necessary changes in the tarball (if I understand things correctly).

Yes, we can do two things:
- Compare the downloaded upstream archive with the archive from lookaside-cache and fail/warn if they differ.
-  Overwrite the archive in lookaside cache on each run.

But still:
- Upload/download takes some time.
- Do we need to support the situation, when upstream change their archive? (The CLI with ` --force-new-sources` is now the only way.)
