### ISSUE TITLE
make it configurable to send events to sentry

### ISSUE THREAD

**Issue by TomasTomecek** [packit-service/packit-service#558]
This is a follow-up to https://github.com/packit-service/packit-service/pull/544

We should have a new packit-service.yaml config option to configure if we want to send events to sentry.

**Comment by IceWreck** [comment]
I'll try tonight. 

Regarding, the setup, if set-up a sentry account, provide sentry credentials in secrets and deploy, then will it automatically start sending events/tracebacks to sentry? Or is there any other config involved too?

**Comment by TomasTomecek** [comment]
You're correct! In p-s [we have this set up via openshift secrets](https://github.com/packit-service/deployment/blob/master/openshift/packit-service-worker.yml.j2#L79), defined [here](https://github.com/packit-service/deployment/blob/master/openshift/secret-sentry.yml.j2) and the content of the secret looks like this: `https://<ugly-string>@sentry.io/<our-id>`

**Comment by IceWreck** [comment]
While working on this, I noticed that while the code to run sentry for the service container is present, its effectively disabled [by not providing SENTRY_SECRET to this container](https://github.com/packit-service/deployment/blob/master/openshift/packit-service.yml.j2)

Secrets are only passed for packit-worker and the fedora-messaging container.

If i do provide them to the service container, it errors out with 
`RuntimeError: Signalling support is unavailable because the blinker library is not installed.`
Sentry docs do not mention needing blinker if `sentry-sdk[flask]` is installed, which is installed, in our case.

Although this is not directly related to this issue, I felt it was worth mentioning / asking about.

**Comment by TomasTomecek** [comment]
@IceWreck good point, would be nice to set up sentry for service pod as well

**Comment by IceWreck** [comment]
👍. I'll start working on setting up sentry for service later this week then.
